### ISSUE TITLE
Save image info in json

### ISSUE THREAD

**Issue by drphilmarshall** [linan7788626/LensWranglerPlusPlus#2]
I think the output json should completely specify the LW++ view, which means it needs to know what the image being worked on is. Can we include the image filename and/or URL in the json, so that the whole thing is loaded in?

**Comment by linan7788626** [comment]
Agree, including the image file name and/or URL should be necessary. I will work on it asap.

**Comment by drphilmarshall** [comment]
Thanks! :-) I guess also the json filename could be related to the image
name, too - if I upload he0435.png, the json I make should be he0435.json.
I'm not sure if the json's should be named uniquely (to allow tracking of
model evolution) but that would be a separate issue anyway :-)

**Comment by linan7788626** [comment]
http://lenszoo.files.wordpress.com/2013/12/asw0009cjs-zoomed.jpg

Hi Phil, 

I tried to load the image above and save the URL and NAME of the image in the JSON file, it seems working. You can upload the URL in the textbox, construct your own model, then press the button "save the model" to export a JSON file named "($imageName).JSON".  I also attached an example of the output JSON file below, please let me know if you have any questions or suggestions. 
Thanks 

Nan Li

> {
>     "name": "asw0009cjs-zoomed",
>     "src": "http://lenszoo.files.wordpress.com/2013/12/asw0009cjs-zoomed.jpg",
>     "components": [
>         {
>             "plane": "source",
>             "size": 1.183,
>             "ell": 2,
>             "ang": 22.135,
>             "x": 0.068,
>             "y": 0.405
>         },
>         {
>             "plane": "lens",
>             "theta_e": 2.077,
>             "ell": 2,
>             "ang": 31.842,
>             "x": -0.54,
>             "y": 0.811
>         }
>     ]
> }

**Comment by drphilmarshall** [comment]
Looks good to me! I can't test it yet though, the example must be using code from a different branch.

**Comment by linan7788626** [comment]
I just pushed the newest version to the web page of the example. I believe you can test it now.
Thanks.

http://linan7788626.github.io/pages/LensWranglerPlusPlus/index.html

**Comment by drphilmarshall** [comment]
Excellent! I too can make a nice JSON file :-)
