### ISSUE TITLE
License

### ISSUE THREAD

**Issue by drphilmarshall** [linan7788626/LensWranglerPlusPlus#6]
We need one. And we should point it out in the README. I guess this should be the same as the LensWrangler one? (I just added the MIT License over there :-) )

**Comment by linan7788626** [comment]
Yes, MIT license sounds good to me. Thanks for your work, you make this project more professional. For your convenience, I just added you as a collaborator, I hope you do not mind this. :-)

**Comment by drphilmarshall** [comment]
Not at all! Thank you :-)
