### ISSUE TITLE
Repo name, contributors

### ISSUE THREAD

**Issue by drphilmarshall** [linan7788626/LensWranglerPlusPlus#9]
@linan7788626 A significant downside of copying a repo rather than forking it is that you lose the communication links to the people on the watchlist of the original. We can address this by inviting the old collaborators to come watch this repo - I'm happy to do that.

Then, I think the project needs a better name: "LensWrangler" was already bad, "LensWrangler++" is worse (even though it is very informative :-) )  Given that we are making something for the citizens, I think we should choose something fun. What do you think of "Hoopla" ? :-)

**Comment by linan7788626** [comment]
> @linan7788626 A significant downside of copying a repo rather than forking it is that you lose the communication links to the people on the watchlist of the original. We can address this by inviting the old collaborators to come watch this repo - I'm happy to do that.

At the beginning, I was just playing with lens wrangler for fun, and wanted to learn something, I did not expect to make it as an actual project. Now, I think your concern makes sense. I am sorry about my carelessness. If you could please invite the old collaborators, I really appreciate it.

> Then, I think the project needs a better name: "LensWrangler" was already bad, "LensWrangler++" is worse (even though it is very informative :-) ) Given that we are making something for the citizens, I think we should choose something fun. What do you think of "Hoopla" ? :-)

Hoopla sounds like an awesome game, and you are good at giving names to apps, I vote this name. :-). Thanks a lot.

**Comment by drphilmarshall** [comment]
No worries, Nan - copying and playing around makes total sense! Especially with the MIT license. I'll contact the others and invite them over. They'll be excited to see this! :-)
